server.port=${PORT:8080}

spring.profiles.active=prod

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# O*NET
onet.api.base-url=https://services.onetcenter.org/ws
onet.api.username=${ONET_API_USERNAME}
onet.api.password=${ONET_API_PASSWORD}

# Adzuna
adzuna.api.base-url=https://api.adzuna.com/v1/api
adzuna.api.app-id=${ADZUNA_APP_ID}
adzuna.api.app-key=${ADZUNA_APP_KEY}

# Webhook
make.webhook.url=${MAKE_WEBHOOK_URL}
make.webhook.resume-url=${MAKE_WEBHOOK_RESUME_URL}

# CORS (IMPORTANT – update later with render URL if needed)
app.cors.allowed-origins=https://career-guidance-and-resume-evaluator.vercel.app
